[[redirects]]
  from = "https://faasandfurious.com"
  to = "https://www.goodtechthings.com"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://www.goodtechthings.com"
  status = 301
  force = true
